parameters:
    oro_user.user_datagrid_manager.class:                 Oro\Bundle\UserBundle\Datagrid\UserDatagridManager
    oro_user.role_datagrid_manager.class:                 Oro\Bundle\UserBundle\Datagrid\RoleDatagridManager
    oro_user.group_datagrid_manager.class:                Oro\Bundle\UserBundle\Datagrid\GroupDatagridManager
    oro_user.role_user_datagrid_manager.class:            Oro\Bundle\UserBundle\Datagrid\RoleUserDatagridManager
    oro_user.group_user_datagrid_manager.class:           Oro\Bundle\UserBundle\Datagrid\GroupUserDatagridManager
    oro_user.email.datagrid_manager.class:                Oro\Bundle\UserBundle\Datagrid\UserEmailDatagridManager

services:
    oro_user.user_datagrid_manager:
        class: %oro_user.user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Oro\Bundle\UserBundle\Entity\User
              entity_hint: user
              flexible: true
              route_name: oro_user_index

    oro_user.role_datagrid_manager:
        class: %oro_user.role_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_roles
              entity_name: Oro\Bundle\UserBundle\Entity\Role
              query_entity_alias: user_role
              entity_hint: role
              route_name: oro_user_role_index

    oro_user.group_datagrid_manager:
        class: %oro_user.group_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_groups
              entity_name: Oro\Bundle\UserBundle\Entity\Group
              query_entity_alias: user_group
              entity_hint: group
              route_name: oro_user_group_index

    oro_user.role_user_datagrid_manager:
        class: %oro_user.role_user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_roleusers
              entity_name: Oro\Bundle\UserBundle\Entity\User
              query_entity_alias: user
              entity_hint: user
              route_name: oro_user_role_user_grid

    oro_user.group_user_datagrid_manager:
        class: %oro_user.group_user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_groupusers
              entity_name: Oro\Bundle\UserBundle\Entity\User
              query_entity_alias: user
              entity_hint: user
              route_name: oro_user_group_user_grid

    oro_user.email.datagrid_manager:
        class: %oro_user.email.datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_emails
              entity_name: %oro_email.email.entity.class%
              query_factory: oro_user.email.datagrid_query_factory
              entity_hint: email
              route_name: oro_user_view

