template_controller:
    name: Actions from template controller
    type: action
    group: ""
    class: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    method: templateAction

external_bundle_actions:
    name: External bundle actions
    type: action
    group: ""

oro_user:
    name: User manipulation
    type: action
    group: ""
