template_controller:
    label: Actions from template controller
    type: action
    group_name: ""
    bindings:
        - {  class: Symfony\Bundle\FrameworkBundle\Controller\TemplateController, method: templateAction}

external_bundle_actions:
    label: External bundle actions
    type: action
    group_name: ""
    bindings: ~

oro_user:
    label: User manipulation
    type: action
    group_name: ""
    bindings: ~
