datagrid:
    users-grid:
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                    - u.created
                    - u.updated
                    - u.enabled
                from:
                    - { table: OroUserBundle:User, alias: u }
        columns:
            username:
                label: oro.user.grid.users.columns.username
                type: field
            email:
                label: oro.user.grid.users.columns.email
                type: field
            firstName:
                label: oro.user.grid.users.columns.firstName
                type: field
            lastName:
                label: oro.user.grid.users.columns.lastName
                type: field
            created:
                label: oro.user.grid.users.columns.created
                type: field
                frontend_type: datetime
            updated:
                label: oro.user.grid.users.columns.created
                type: field
                frontend_type: datetime
            enabled:
                label: oro.user.grid.users.columns.enabled
                type: field
                frontend_type: boolean
        properties:
            update_link:
                type: url
                route: oro_user_update
                params:
                    - id

            view_link:
                type: url
                route: oro_user_view
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstname:
                    data_name: u.firstName
                lastname:
                    data_name: u.lastName
                created:
                    data_name: u.created
                updated:
                    data_name: u.updated
                enabled:
                    data_name: u.enabled
            default:
                username: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC

        filters:
            columns:
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstname:
                    type: string
                    data_name: u.firstName
                lastname:
                    type: string
                    data_name: u.lastName
                created:
                    type: datetime
                    data_name: u.created
                updated:
                    type: datetime
                    data_name: u.updated
                enabled:
                    type: choice
                    data_name: u.enabled

    groups-grid:
        source:
            acl_resource: oro_user_group_view
            type: orm
            query:
                select:
                    - g.id
                    - g.name
                from:
                    - { table: OroUserBundle:Group, alias: g }
        columns:
            id:
                type: field
            name:
                type: field

        properties:
            update_link:
                type: url
                route: oro_user_group_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_group
                params:
                    - id
        sorters:
            columns:
                name:
                    data_name: g.name
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                name:
                    type: string
                    data_name: g.name

    roles-grid:
        source:
            acl_resource: oro_user_role_view
            type: orm
            query:
                select:
                    - r.id
                    - r.role
                    - r.label
                from:
                    - { table: OroUserBundle:Role, alias: r }
                where:
                    and:
                        - r.role <> '%oro_user.entity.class%::ROLE_ANONYMOUS'
        columns:
            label:
                type: field

        properties:
            update_link:
                type: url
                route: oro_user_role_update
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_role
                params:
                    - id
        sorters:
            columns:
                label:
                    data_name: r.label
            default:
                label: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                label:
                    type: string
                    data_name: r.label

    users-email-grid:
        extend: email-grid
        source:
            query:
                join:
                    inner:
                        folder:
                            join: e.folder
                            alias: f
                        origin:
                            join: f.origin
                            alias: o
                where:
                    and:
                        - o.id = :origin_id

    user-relation-grid:
        source:
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                from:
                    - { table: OroUserBundle:User, alias: u }

        columns:
            id:
                label: ID
                type: field
                frontend_type: integer
            username:
                label: Username
                type: field
                frontend_type: string
            email:
                label: Email
                type: field
                frontend_type: string
            firstName:
                label: First name
                type: field
                frontend_type: string
            lastName:
                label: Last name
                type: field
                frontend_type: string

        properties: ~

        sorters:
            columns:
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstname:
                    data_name: u.firstName
                lastname:
                    data_name: u.lastName
            default:
                id: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

        filters:
            columns:
                username:
                    type: string
                    data_name: u.username
                email:
                    type: string
                    data_name: u.email
                firstname:
                    type: string
                    data_name: u.firstName
                lastname:
                    type: string
                    data_name: u.lastName

    role-users-grid:
        extend: user-relation-grid
        source:
            acl_resource: oro_user_role_update
            query:
                select:
                    - >
                      (CASE WHEN (:role_id IS NOT NULL) THEN
                        CASE WHEN (:role_id MEMBER OF u.roles OR u.id IN (:data_in)) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN u.id IN (:data_in) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as has_role
        columns:
            has_role:
                label: Has role
                type: field
                frontend_type: boolean
        filters:
            columns:
                has_role:
                    type: boolean
                    data_name: has_role
        sorters:
            columns:
                has_role:
                    data_name: has_role
            default:
                has_role: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
                lastName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

    group-users-grid:
        extend: user-relation-grid
        source:
            acl_resource: oro_user_group_update
            query:
                select:
                    - >
                      (CASE WHEN (:group_id IS NOT NULL) THEN
                        CASE WHEN (:group_id MEMBER OF u.groups OR u.id IN (:data_in)) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      ELSE
                        CASE WHEN u.id IN (:data_in) AND u.id NOT IN (:data_not_in)
                        THEN true ELSE false END
                      END) as has_group
        columns:
            has_group:
                label: Has group
                type: field
                frontend_type: boolean
        filters:
            columns:
                has_group:
                    type: boolean
                    data_name: has_group
        sorters:
            columns:
                has_group:
                    data_name: has_group
            default:
                has_group: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_DESC
                lastName: %oro_datagrid.extension.orm_sorter.class%::DIRECTION_ASC

    # TODO: Move this to OroCRMContactBundle
    contacts-email-grid:
        extend: email-grid
        source:
            query:
                where:
                    and:
                        - a.email IN (:email_addresses)
