parameters:
    oro_user.user_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\UserDatagridManager
    oro_user.role_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\RoleDatagridManager
    oro_user.group_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\GroupDatagridManager
    oro_user.role_user_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\RoleUserDatagridManager
    oro_user.group_user_datagrid_manager.class: Oro\Bundle\UserBundle\Datagrid\GroupUserDatagridManager

services:
    oro_user.user_datagrid_manager:
        class: %oro_user.user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: users
              entity_name: Oro\Bundle\UserBundle\Entity\User
              entity_hint: users
              flexible: true
              route_name: oro_user_index
              identifier_field: id

    oro_user.role_datagrid_manager:
        class: %oro_user.role_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_roles
              entity_name: Oro\Bundle\UserBundle\Entity\Role
              entity_hint: roles
              route_name: oro_user_role_index
              identifier_field: id

    oro_user.group_datagrid_manager:
        class: %oro_user.group_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_groups
              entity_name: Oro\Bundle\UserBundle\Entity\Group
              query_entity_alias: user_group
              entity_hint: groups
              route_name: oro_user_group_index
              identifier_field: id

    oro_user.role_user_datagrid_manager:
        class: %oro_user.role_user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_roleusers
              entity_name: Oro\Bundle\UserBundle\Entity\User
              query_entity_alias: user
              entity_hint: users
              route_name: oro_user_role_user_grid
              identifier_field: id

    oro_user.group_user_datagrid_manager:
        class: %oro_user.group_user_datagrid_manager.class%
        tags:
            - name: oro_grid.datagrid.manager
              datagrid_name: user_groupusers
              entity_name: Oro\Bundle\UserBundle\Entity\User
              query_entity_alias: user
              entity_hint: users
              route_name: oro_user_group_user_grid
              identifier_field: id
