datagrid:
    users-grid:
        source:
            acl_resource: oro_user_user_view
            type: orm
            query:
                select:
                    - u.id
                    - u.username
                    - u.email
                    - u.firstName
                    - u.lastName
                    - u.created
                    - u.updated
                    - u.enabled
                from:
                    - { table: OroUserBundle:User, alias: u }

        columns:
            id:
                type: field

            firstname:
                type: field

        properties:
            update_link:
                type: url
                route: oro_user_update
                params:
                    - id

            view_link:
                type: url
                route: oro_user_view
                params:
                    - id

            delete_link:
                type: url
                route: oro_api_delete_user
                params:
                    - id
        sorters:
            columns:
                id:
                    data_name: u.id
                username:
                    data_name: u.username
                email:
                    data_name: u.email
                firstname:
                    data_name: u.firstName
                lastname:
                    data_name: u.lastName

            default:
                label: %oro_grid.extension.orm_sorter.class%::DIRECTION_DESC
