oro_menu_config:
    items:
        system_tab:
            label: 'System'
            uri: '#'
        users_management:
            label: 'Users Management'
            uri: '#'
        user_list:
            label: 'Users'
            route: 'oro_user_index'
            extras:
                routes: ['/^oro_user_(?!role\w+|group\w+|security\w+|reset\w+)\w+$/']
                description: List of all system users
        user_create:
            label: 'Create User'
            route: 'oro_user_create'
        user_roles:
            label: 'Roles'
            route: 'oro_user_role_index'
            extras:
                routes: ['oro_user_role_*']
                description: List of all system roles
        user_groups:
            label: 'Groups'
            route: 'oro_user_group_index'
            extras:
                routes: ['oro_user_group_*']
                description: List of all system groups
        shortcut_new_user:
            label: Create new user
            route: oro_user_create
            extras:
                description: Create new user instance
                isCustomAction: true
        shortcut_list_users:
            label: Show users list
            route: oro_user_index
            extras:
                description: List of all system users
                isCustomAction: true
        shortcut_new_role:
            label: Create new role
            route: oro_user_role_create
            extras:
                description: Create new role instance
        shortcut_new_group:
            label: Create new group
            route: oro_user_group_create
            extras:
                description: Create new group instance

    tree:
        application_menu:
            children:
                system_tab:
                    children:
                        users_management:
                            children:
                                user_list: ~
                                user_roles: ~
                                user_groups: ~

        shortcuts:
            children:
                shortcut_new_user: ~
                shortcut_list_users: ~
                shortcut_new_role: ~
                shortcut_new_group: ~

oro_titles:
    oro_user_view: %%username%%
    oro_user_update: Edit %%username%%
    oro_user_create: Create User
    oro_user_index: ~

    oro_user_role_update: Edit %%role%%
    oro_user_role_create: Create Role
    oro_user_role_index: ~

    oro_user_security_login: Login
    oro_user_status_list: "User Status"
    oro_user_status_create: "Add Status"

    oro_user_reset_reset: Password Reset
    oro_user_reset_request: Forgot Password
    oro_user_reset_check_email: Password Reset - Check Email

    oro_user_group_create: Create Group
    oro_user_group_update: Edit %%group%%
    oro_user_group_index: ~
