Oro\Bundle\UserBundle\Entity\User:
    alias:                          oro_user
    flexible_manager:               oro_user.manager.flexible
    title_fields:                   [username]
    route:
        name:                       oro_user_view
        parameters:
            id:                     id
    search_template:                OroUserBundle:Search:result.html.twig
    fields:
        -
            name:                   username
            target_type:            text
            target_fields:          [username]
        -
            name:                   email
            target_type:            text
            target_fields:          [email]
        -
            name:                   firstName
            target_type:            text
            target_fields:          [firstName]
        -
            name:                   lastName
            target_type:            text
            target_fields:          [lastName]
        -
            name:                   birthday
            target_type:            birthday
            target_fields:          [birthday]
