parameters:
    oro_user.manager.class:             Oro\Bundle\UserBundle\Entity\UserManager
    oro_user.manager.flexible.class:    Oro\Bundle\FlexibleEntityBundle\Manager\FlexibleManager
    oro_user.manager.api.class:         Oro\Bundle\SoapBundle\Entity\Manager\ApiFlexibleEntityManager
    oro_user.status.manager.class:      Oro\Bundle\UserBundle\Entity\Manager\StatusManager
    oro_user.entity.class:              Oro\Bundle\UserBundle\Entity\User
    oro_user.entity.value.class:        Oro\Bundle\UserBundle\Entity\UserValue
    oro_user.group.entity.class:        Oro\Bundle\UserBundle\Entity\Group
    oro_user.role.entity.class:         Oro\Bundle\UserBundle\Entity\Role
    oro_user.acl.entity.class:          Oro\Bundle\UserBundle\Entity\Acl
    oro_user.security.provider.class:   Oro\Bundle\UserBundle\Security\UserProvider
    oro_user.security.login.class:      Oro\Bundle\UserBundle\EventListener\LoginSubscriber
    oro_user.user_menu.builder.class:   Oro\Bundle\UserBundle\Menu\UserMenuBuilder
    oro_user.role.listener.class:       Oro\Bundle\UserBundle\EventListener\RoleListener
    oro_user.role.manager.class:        Oro\Bundle\UserBundle\Entity\Manager\RoleManager
    oro_user.role.manager.api.class:    Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_user.group.manager.class:       Oro\Bundle\UserBundle\Entity\Manager\GroupManager
    oro_user.group.manager.api.class:   Oro\Bundle\SoapBundle\Entity\Manager\ApiEntityManager
    oro_user.attribute_type.user.class: Oro\Bundle\UserBundle\AttributeType\UserType
    oro_user.entity_with_image.subscriber.class:  Oro\Bundle\UserBundle\Entity\EventListener\UploadedImageSubscriber
    oro_user.autocomplete.user.search_handler:    Oro\Bundle\UserBundle\Autocomplete\UserSearchHandler
    oro_user.email.owner.provider.class: Oro\Bundle\UserBundle\Entity\Provider\EmailOwnerProvider
    oro_user.gender_provider.class:     Oro\Bundle\UserBundle\Provider\GenderProvider

services:
    oro_user.manager.flexible:
        class:                        "%oro_user.manager.flexible.class%"
        arguments:                    [%oro_user.entity.class%, %oro_flexibleentity.flexible_config%, "@doctrine.orm.entity_manager", "@event_dispatcher", @oro_flexibleentity.attributetype.factory]
        tags:
            - { name: oro_flexibleentity_manager, entity: %oro_user.entity.class%}
        calls:
            - [ addAttributeType, ['oro_flexibleentity_text'] ]
            - [ addAttributeType, ['oro_flexibleentity_textarea'] ]
            - [ addAttributeType, ['oro_flexibleentity_money'] ]
            - [ addAttributeType, ['oro_flexibleentity_simpleselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_multiselect'] ]
            - [ addAttributeType, ['oro_flexibleentity_url'] ]

    oro_user.manager:
        class:                        %oro_user.manager.class%
        arguments:                    [%oro_user.entity.class%, "@doctrine.orm.entity_manager", "@oro_user.manager.flexible", "@security.encoder_factory"]

    oro_user.manager.api:
        class: %oro_user.manager.api.class%
        arguments:
            - %oro_user.entity.class%
            - @doctrine.orm.entity_manager
            - @oro_user.manager.flexible

    oro_user.security.provider:
        class:                        %oro_user.security.provider.class%
        public:                       false
        arguments:                    ["@oro_user.manager"]

    oro_user.security.login:
        class:                        %oro_user.security.login.class%
        arguments:                    ["@oro_user.manager"]
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }

    oro_user.cache:
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ "oro_user.cache" ] ]

    oro_user.user_menu:
        class:                        %oro_user.user_menu.builder.class%
        arguments:
            - @security.context
        tags:
            - { name: oro_menu.builder, alias: usermenu }

    oro_user.role.listener:
        class:                        %oro_user.role.listener.class%
        tags:
            - { name: doctrine.event_listener, event: preUpdate }

    oro_user.twig.user_extension:
        class:                        %oro_user.acl.twig.class%
        arguments:                    ["@oro_user.gender_provider"]
        tags:
            - { name: twig.extension }

    oro_user.status_manager:
        class:                        %oro_user.status.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager", "@oro_user.manager"]

    oro_user.role_manager:
        class:                        %oro_user.role.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_user.role_manager.api:
        class: %oro_user.role.manager.api.class%
        arguments:
            - %oro_user.role.entity.class%
            - @doctrine.orm.entity_manager

    oro_user.group_manager:
        class:                        %oro_user.group.manager.class%
        arguments:                    ["@doctrine.orm.entity_manager"]

    oro_user.group_manager.api:
        class: %oro_user.group.manager.api.class%
        arguments:
            - %oro_user.group.entity.class%
            - @doctrine.orm.entity_manager

    # Flexible attribute
    oro_user.attribute_type.user:
        class: %oro_user.attribute_type.user.class%
        arguments:
            - "user"
            - "oro_user_select"
            - @oro_flexibleentity.validator.attribute_constraint_guesser
        tags:
            - { name: oro_flexibleentity.attributetype, alias: oro_user_attribute_user }

    oro_user.entity_with_image.subscriber:
        class: %oro_user.entity_with_image.subscriber.class%
        arguments:
            - %kernel.root_dir%
        tags:
            - { name: doctrine.event_subscriber }

    # Autocomplete search handler
    oro_user.autocomplete.user.search_handler:
        class: %oro_user.autocomplete.user.search_handler%
        parent: oro_form.autocomplete.search_handler
        arguments:
            - @liip_imagine.cache.manager
            - %oro_user.entity.class%
            - ["username", "firstName", "lastName", "email"]
        tags:
            - { name: oro_form.autocomplete.search_handler, alias: users, acl_resource: oro_user_user_list }

    oro_user.gender_provider:
        class: %oro_user.gender_provider.class%
        arguments:
            - @translator

    oro_user.email.owner.provider:
        class: %oro_user.email.owner.provider.class%
        tags:
            - { name: oro_email.owner.provider, order: 1 }

