services:
    oro_user.api.create.save_entity:
        class: Oro\Bundle\UserBundle\Api\Processor\Create\SaveEntity
        arguments:
            - '@oro_user.manager'
        tags:
            - { name: oro.api.processor, action: create, group: save_data, class: Oro\Bundle\UserBundle\Entity\User }
