oro_system_configuration:
    groups:
        others:
            title: 'Others'
            priority: -255

    fields:
        oro_user.name_format:
            type: text
            options:
                label: 'Name format'
                required: true
                #tooltip: 'Available variables:<br> %%firstname%%, %%lastname%%'
                constraints:
                    - NotBlank: ~

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            localization:
                                children:
                                    others:
                                        children:
                                            - oro_user.name_format
