oro_system_configuration:
    groups:
        user_output:
            title: 'User output format'
            description: 'Those setting related to output format of user entity'

        some_group:
            priority: 30
            title: 'Some group'

    fields:
        oro_user.name_format:
            type: choice
            options:
               label: 'Name format'
               required: true
               constraints:
                  - NotBlank: ~
               choices:
                  '%%first%% %%last%%': '%%first%% %%last%%'
                  '%%last%% %%first%%': '%%last%% %%first%%'
            priority: 20
    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            application_information:
                                children:
                                    user_output:
                                        priority: 20
                                        children:
                                            - oro_user.name_format

