operations:
    DELETE:
        exclude_datagrids:
            - owner-users-select-grid
        exclude_entities:
            - Oro\Bundle\UserBundle\Entity\Role
            - Oro\Bundle\UserBundle\Entity\User
    clone_role:
        extends: CLONE
        order: 4
        datagrids:
            - roles-grid
        routes:
            - oro_user_role_index
            - oro_user_role_update
            - oro_user_role_view
        acl_resource: [CREATE, entity:Oro\Bundle\UserBundle\Entity\Role]
        preactions:
            - '@tree':
                conditions:
                    '@and':
                        - '@eq': [$.requestRoute, 'oro_action_widget_form']
                actions:
                    - '@trans':
                        id: oro.action.clone.label
                        attribute: $.clone.label
                        params:
                            '{label}': $.clone.label
                    - '@call_service_method':
                        attribute: $.aclRoleHandler
                        service: service_container
                        method: get
                        method_parameters: ['oro_user.form.handler.acl_role']
                    - '@call_method':
                        object: $.aclRoleHandler
                        method: createForm
                        method_parameters: [$.clone]
                    - '@call_method':
                        object: $.aclRoleHandler
                        method: process
                        method_parameters: [$.data]
                    - '@call_method':
                        attribute: $.formView
                        object: $.aclRoleHandler
                        method: createView
                    - '@call_service_method':
                        attribute: $.privilegesConfig
                        service: service_container
                        method: getParameter
                        method_parameters: ['oro_user.privileges']
                    - '@call_service_method':
                        attribute: $.categoryProvider
                        service: service_container
                        method: get
                        method_parameters: ['oro_user.provider.role_privilege_category_provider']
                    - '@call_method':
                        attribute: $.tabs
                        object: $.categoryProvider
                        method: getTabs
                    - '@call_service_method':
                        attribute: $.privilegeCapabilityProvider
                        service: service_container
                        method: get
                        method_parameters: ['oro_user.provider.role_privilege_capability_provider']
                    - '@call_method':
                        attribute: $.capabilitySetOptions
                        object: $.privilegeCapabilityProvider
                        method: getCapabilitySetOptions
                        method_parameters: [$.data]
        frontend_options:
            show_dialog: false
            template: 'OroUserBundle:Role:clone.html.twig'
        attributes:
            entity:
                label: ' '
                type: entity
                options:
                  class: 'Oro\Bundle\UserBundle\Entity\Role'
        form_options:
            attribute_fields:
                entity:
                    form_type: form
    oro_user_edit_role:
        label: oro.user.role.actions.edit
        routes:
            - oro_user_role_view
        acl_resource: [EDIT, entity:Oro\Bundle\UserBundle\Entity\Role]
        order: 10
        groups:
            - view_navButtons
        button_options:
            icon: icon-edit
        actions:
            - '@redirect':
                parameters:
                    route: oro_user_role_update
                    route_parameters:
                        id: $id
    reset_password:
        label: oro.user.password.reset_password.label
        entities:
            - Oro\Bundle\UserBundle\Entity\User
        groups:
            - datagridRowAction
        datagrids:
            - users-grid
        routes:
            - oro_user_index
            - oro_user_view
        order: 50
        acl_resource: [password_management]
        button_options:
            icon: icon-shield
        frontend_options:
            confirmation:
                title: oro.user.reset_password.popup.title
                okText: oro.user.reset_password.popup.label
                message: oro.user.reset_password.popup.question
                message_parameters:
                    user: $.data.username
                component: oroui/js/standart-confirmation
        datagrid_options:
            mass_action:
                type: resetpassword
                label: oro.user.password.reset_password.label
                icon: shield
                route: oro_user_mass_password_reset
                data_identifier: u.id
                confirmation: true
                defaultMessages:
                    confirm_title: oro.user.reset_password.mass_action.title
                    confirm_content: oro.user.reset_password.mass_action.question
                    confirm_ok: oro.user.reset_password.mass_action.label
                acl_resource: password_management
                frontend_options:
                    title: oro.user.reset_password.popup.title
                    dialogOptions:
                        modal: true
                messages:
                    - success: oro.user.password.force_reset.mass_action.success
                    - failure: oro.user.password.force_reset.mass_action.failure
        actions:
            - '@call_method':
                object: $.data
                method: setLoginDisabled
                method_parameters: [true]
            - '@call_method':
                object: $.data
                method: getConfirmationToken
                attribute: $.token
            - '@tree':
                conditions:
                    '@and':
                        - '@empty': $.token
                actions:
                    - '@call_method':
                        object: $.data
                        method: generateToken
                        attribute: $.token
                    - '@call_method':
                        object: $.data
                        method: setConfirmationToken
                        method_parameters: [$.token]
            - '@flush_entity': $.data
            - '@call_service_method':
                service: oro_user.mailer.processor
                method: sendForcedResetPasswordAsAdminEmail
                method_parameters: [$.data]
                attribute: $.sent
            - '@tree':
                conditions:
                    '@and':
                        - '@eq': [$.sent, true]
                actions:
                    - '@flash_message':
                        message: oro.user.password.force_reset.success.message
                        type: 'success'
            - '@tree':
                conditions:
                    '@and':
                        - '@eq': [$.sent, false]
                actions:
                    - '@flash_message':
                        message: oro.user.password.force_reset.failure.message
                        type: 'error'
