api:
    entities:
        Oro\Bundle\UserBundle\Entity\Group: ~
        Oro\Bundle\UserBundle\Entity\Role:
            delete_handler: oro_user.role.handler.delete

        Oro\Bundle\UserBundle\Entity\User:
            delete_handler: oro_user.handler.delete
            fields:
                emails:
                    data_type: array
                    exclusion_policy: all
                    fields:
                        email: ~
            actions:
                delete:
                    exclude: false # set manually because this entity is marked as a dictionary
                delete_list:
                    exclude: false # set manually because this entity is marked as a dictionary
                create:
                    exclude: false # set manually because this entity is marked as a dictionary
                update:
                    exclude: false # set manually because this entity is marked as a dictionary

        Oro\Bundle\UserBundle\Entity\Email:
            # this entity does not have own Data API resource
            actions: false
