hwi_oauth:
    firewall_name: main
    resource_owners:
        google:
            type: google
            client_id: %google.client_id%
            client_secret: %google.client_secret%
            scope: "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile"
