elements:
  Login Form:
    selector: '#login-form'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Form
    options:
      mapping:
        Username: '_username'
        Password: '_password'

  User Form:
    selector: 'div#container'
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Form
    options:
      mapping:
        Username: 'oro_user_user_form[username]'
        Password: 'oro_user_user_form[plainPassword][first]'
        Re-Enter Password: 'oro_user_user_form[plainPassword][second]'
        First Name: 'oro_user_user_form[firstName]'
        Last Name: 'oro_user_user_form[lastName]'
        Primary Email: 'oro_user_user_form[email]'

  UserMenu:
    selector: {type: 'xpath', locator: '//li[@id="user-menu"]'}
    class: Oro\Bundle\TestFrameworkBundle\Behat\Element\Element

  UserRoleForm:
    selector: "form[id^='oro_user_role_form']"
    class: Oro\Bundle\UserBundle\Tests\Behat\Element\UserRoleForm

pages:
  Login:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\Login
    route: 'oro_user_security_login'

  User Profile View:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\UserProfileView
    route: 'oro_user_profile_view'

  User Profile Configuration:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\UserProfileConfiguration
    route: 'oro_user_profile_configuration'

  User Index:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\UserIndex
    route: 'oro_user_index'

  User Create:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\UserCreate
    route: 'oro_user_create'

  User View:
    class: Oro\Bundle\UserBundle\Tests\Behat\Page\UserView
    route: 'oro_user_view'
