oro_entity_virtual_fields:
    Oro\Bundle\UserBundle\Entity\User:
        primaryEmail:
            query:
                select:
                    expr:         emails.email
                    return_type:  string
                join:
                    left:
                        - { join: entity.emails, alias: emails, conditionType: 'WITH', condition: 'emails.primary = true' }
