system_configuration:
    groups:
        user_settings:
            icon:  icon-key
            title: oro.user.system_configuration.groups.user_settings.title
        failed_login_limit:
           icon: icon-signin
           title: oro.user.system_configuration.groups.failed_login_limit.title
        password_complexity_rules:
            icon:  icon-usd
            title: oro.user.system_configuration.groups.password_complexity_rules.title
        mandatory_password_change:
            icon:  icon-repeat
            title: oro.user.system_configuration.groups.mandatory_password_change.title

    fields:
        oro_user.failed_login_limit_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 80
            options:
                required: false
                label: oro.user.system_configuration.fields.failed_login_limit_enabled.label
        oro_user.failed_login_limit:
            data_type: integer
            type: integer
            priority: 70
            options:
                label: oro.user.system_configuration.fields.failed_login_limit.label
                constraints:
                    - GreaterThan:
                        value: 0
        oro_user.password_min_length:
            data_type: integer
            type: integer
            priority: 40
            options:
                label:  oro.user.system_configuration.fields.password_min_length.label
                constraints:
                    - Range:
                        min: 1

        oro_user.password_numbers:
            data_type: boolean
            type: oro_config_checkbox
            priority: 30
            options:
                label: oro.user.system_configuration.fields.password_numbers.label
                required: false

        oro_user.password_upper_case:
            data_type: boolean
            type: oro_config_checkbox
            priority: 20
            options:
                label: oro.user.system_configuration.fields.password_upper_case.label
                required: false

        oro_user.password_special_chars:
            data_type: boolean
            type: oro_config_checkbox
            priority: 10
            options:
                label: oro.user.system_configuration.fields.password_special_chars.label
                tooltip: oro.user.system_configuration.fields.password_special_chars.tooltip
                required: false

        oro_user.days_before_change_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 99
            options:
                required: false
                label: oro.user.system_configuration.fields.days_before_change_enabled.label
        oro_user.days_before_change:
            data_type: integer
            type: integer
            priority: 89
            options:
                label: oro.user.system_configuration.fields.days_before_change.label
                constraints:
                    - GreaterThan:
                        value: 0
        oro_user.match_old_passwords_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 79
            options:
                required: false
                label: oro.user.system_configuration.fields.match_old_passwords_enabled.label
        oro_user.match_old_passwords_number:
            data_type: integer
            type: integer
            priority: 69
            options:
                label: oro.user.system_configuration.fields.match_old_passwords_number.label
                constraints:
                    - GreaterThan:
                        value: 0

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            user_settings:
                                priority: 100
                                children:
                                    failed_login_limit:
                                        children:
                                            - oro_user.failed_login_limit_enabled
                                            - oro_user.failed_login_limit
                                    password_complexity_rules:
                                        children:
                                            - oro_user.password_min_length
                                            - oro_user.password_numbers
                                            - oro_user.password_upper_case
                                            - oro_user.password_special_chars
                                    mandatory_password_change:
                                        children:
                                            - oro_user.days_before_change_enabled
                                            - oro_user.days_before_change
                                            - oro_user.match_old_passwords_enabled
                                            - oro_user.match_old_passwords_number
