system_configuration:
    groups:
       user_settings:
           icon:  icon-key
           title: oro.user.system_configuration.groups.user_settings.title
       failed_login_limit:
           icon: icon-signin
           title: oro.user.system_configuration.groups.failed_login_limit.title

    fields:
        oro_user.failed_login_limit_enabled:
            data_type: boolean
            type: oro_config_checkbox
            priority: 80
            options:
                required: false
                label: oro.user.system_configuration.fields.failed_login_limit_enabled.label
        oro_user.failed_login_limit:
            data_type: integer
            type: integer
            priority: 70
            options:
                label: oro.user.system_configuration.fields.failed_login_limit.label
                constraints:
                    - GreaterThan:
                        value: 0

    tree:
        system_configuration:
            platform:
                children:
                    general_setup:
                        children:
                            user_settings:
                                priority: 90
                                children:
                                    failed_login_limit:
                                        children:
                                            - oro_user.failed_login_limit_enabled
                                            - oro_user.failed_login_limit
